title: SimpleXMQ for StartOS Usage Instructions
email: shyfire131@shyfire131.net
description: >- # this means to ignore newlines until "baseurl:"
  Usage instructions for the SimplexMQ service wrapper on StartOS.
baseurl: "startOS-simplexMQ-wrapper" 
url: "https://shyfire131.github.io" 
twitter_username: shyfire131
github_username:  shyfire131

# Build settings
theme: minima
plugins:
  - jekyll-feed